"""empty message

Revision ID: 4fb101d484ed
Revises: d7f9f52c81a9
Create Date: 2024-12-28 11:38:01.691724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb101d484ed'
down_revision = 'd7f9f52c81a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('progress_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress')
    # ### end Alembic commands ###
